config/routes.rb
Rails.application.routes.draw do
  devise_for :customers do
    get "/customers/sign_up" => "devise/registrations#new", :as => :new_customer_registration_path
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :categories
  resources :orders
  resources :products do
    collection do
      get "search"
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "products#index"
  get "/contact", to: "contact#index", as: "contact" # contact_path
  get "/about", to: "about#index", as: "about" # about_path

  get "/shopping_cart", to: "cart#index", as: "shopping_cart" # cart_path

  scope "/checkout" do
    post "create", to: "checkout#create", as: "checkout_create"
    get "success", to: "checkout#success", as: "checkout_success"
    get "cancel", to: "checkout#cancel", as: "checkout_cancel"
  end
end

app/models/about.rb
class About < ApplicationRecord
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :Customer
  validates :address, :city, :postal_code, presence: true
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :nullify
  validates :category_name, presence: true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_line_items, dependent: :nullify
  has_many :products, through: :order_line_items
  belongs_to :Tax
  validates :total_amount, presence: true
  accepts_nested_attributes_for :order_line_items, allow_destroy: true
end

app/models/order_line_item.rb
class OrderLineItem < ApplicationRecord
  belongs_to :Order
  belongs_to :Product
  validates :price, :quantity, :total_tax_rate, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :Category
  has_many :order_line_items, dependent: :nullify
  has_many :orders, through: :order_line_items
  validates :product_name, :price, presence: true
  accepts_nested_attributes_for :order_line_items, allow_destroy: true
  has_one_attached :image
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :address, dependent: :nullify
end

app/models/tax.rb
class Tax < ApplicationRecord
  has_many :order_line_items, dependent: :nullify
  validates :pst, :gst, :hst, :total_tax_rate, presence: true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
    @abouts = About.all
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
    @contacts = Contact.all
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[show edit update destroy]

  # GET /orders or /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1 or /orders/1.json
  def show; end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit; end

  # POST /orders or /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to order_url(@order), notice: "Order was successfully created." }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1 or /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to order_url(@order), notice: "Order was successfully updated." }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1 or /orders/1.json
  def destroy
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url, notice: "Order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_order
    @order = Order.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def order_params
    params.fetch(:order, {})
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[show edit update destroy]

  # GET /products or /products.json
  def index
    @products = Product.order(created_at: :asc).page(params[:page])
  end

  # GET /products/1 or /products/1.json
  def show
    @product = Product.find(params[:id])
  end

  def search
    wildcard_search = "%#{params[:keywords]}%"
    if params[:category] == ""
      @products = Product.where("product_name LIKE ?", wildcard_search)
    else
      @products = Product.where("product_name LIKE ?", wildcard_search).where("category_id = ?",
                                                                              params[:category])
    end
  end

  # GET /products/new
  # def new
  #   @product = Product.new
  # end

  # GET /products/1/edit
  def edit; end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)
    respond_to do |format|
      if @product.save
        format.html do
          redirect_to product_url(@product), notice: "Product was created."
        end
        format.json { render :show, status: :created, location: @product }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html do
          redirect_to product_url(@product), notice: "Product was updated."
        end
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def product_params
    params.fetch(:product, {})
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
    <h2><%= product.product_name %></h2>
    <p>
        <div>Category: <%= product.Category.category_name %></div>
        <div>Price: $<%= product.price %></div>
        <div>Description: <%= product.description %></div>
        <br>
    </p>

    <% if product.image.present? %>
        <div class="card-image">
        <figure class="image">
            <%= image_tag(product.image, size:"250x250") %>
        </figure>
        </div>
    <% end %>
</div>

<% if cart.include?(product) %>
    <%= button_to cart_path(product), method: :delete do %>
        Remove from cart
    <% end %>
<% else %>
    <%= form_with url: cart_index_path, method: :post do %>
        <%= hidden_field_tag(:id, product.id) %>
        <%= button_tag 'Add to cart' %>

    <% end %>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Green Bean Products</h1>

<nav class="pagination" role="navigation" aria-label="pagination"><%= paginate @products %> </nav>
<div id="products">

  <% @products.each do |product| %>
    <p>
      <%= link_to product.product_name, product %>
    </p>
  <% end %>
</div>
<nav class="pagination" role="navigation" aria-label="pagination"><%= paginate @products %> </nav>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/search.html.erb
<div class="container">
  <h3 class="title is-3">
  Found <%= pluralize(@products.count, 'products') %>  found when searching for keyword: <%= params[:keywords] %>
  </h3>
  <div class="content">
    <ul>
      <% @products.each do |prod| %>
        <li><%= link_to prod.product_name, prod %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product %>