config/routes.rb
Rails.application.routes.draw do
  devise_for :customers do
    get "/customers/sign_up" => "devise/registrations#new", :as => :new_customer_registration_path
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :categories
  resources :orders
  resources :products do
    collection do
      get "search"
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "products#index"
  get "/contact", to: "contact#index", as: "contact" # contact_path
  get "/about", to: "about#index", as: "about" # about_path

  get "/shopping_cart", to: "cart#index", as: "shopping_cart" # cart_path

  scope "/checkout" do
    post "create", to: "checkout#create", as: "checkout_create"
    get "success", to: "checkout#success", as: "checkout_success"
    get "cancel", to: "checkout#cancel", as: "checkout_cancel"
  end
end

app/models/about.rb
class About < ApplicationRecord
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :Customer
  validates :address, :city, :postal_code, presence: true
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :nullify
  validates :category_name, presence: true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_line_items, dependent: :nullify
  has_many :products, through: :order_line_items
  belongs_to :Tax
  validates :total_amount, presence: true
  accepts_nested_attributes_for :order_line_items, allow_destroy: true
end

app/models/order_line_item.rb
class OrderLineItem < ApplicationRecord
  belongs_to :Order
  belongs_to :Product
  validates :price, :quantity, :total_tax_rate, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :Category
  has_many :order_line_items, dependent: :nullify
  has_many :orders, through: :order_line_items
  validates :product_name, :price, presence: true
  accepts_nested_attributes_for :order_line_items, allow_destroy: true
  has_one_attached :image
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :address, dependent: :nullify
end

app/models/tax.rb
class Tax < ApplicationRecord
  has_many :order_line_items, dependent: :nullify
  validates :pst, :gst, :hst, :total_tax_rate, presence: true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
    @abouts = About.all
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/cart/index.html.erb
<summary>
    Cart
    <% if cart.present? %>
        <sup><%= cart.size %></sup>
    <% end %>
</summary>
<% if cart.present? %>
    <div>
        <table>
            <thead>
            <tr>
                <th>Product Name</th>
                <th>Price</th>
            </tr>
            </thead>
            <tbody>
            <% cart.each do | item | %>
                <tr>
                <td><%= link_to item.product_name, Product.find(item.id) %> <%= button_to 'Remove', cart_path(item.id), method: :delete, form_class: "btnRemove" %></td>
                <td><sup>$</sup><%= item.price %></td>
                </tr>
            <% end %>
            </tbody>
        </table>
    </div>
<% else %>
    <p>No items in your cart.</p>
<% end %>

app/views/layouts/_menu.html.erb
<div>
  <nav class="navbar" aria-label="main navigation">
    <div class="navbar-menu">
      <div class="navbar-start">
        <div class="navbar-item has-text-weight-bold"><%= link_to "Home", root_path %></div>
        <div class="navbar-item"><%= link_to "Products", root_path %></div>
        <div class="navbar-item"><%= link_to "Category", categories_path %></div>
        <div class="navbar-item"><%= link_to "Contact", contact_path %></div>
        <div class="navbar-item"><%= link_to "About", about_path %></div>
        <% if customer_signed_in? %>
          <div class="navbar-item"> Welcome <%= current_customer.email %> </div>
          <div class="navbar-item"><%= button_to  "Sign out", destroy_customer_session_path, method: :delete %> </div>
        <% else %>
          <div class="navbar-item"><%= button_to  "Sign In", customer_session_path %> </div>
          <%# <div class="navbar-item"><%= button_to  "Register", new_customer_registration_path %>
          <div class="navbar-item"><button onclick="location.replace('/customers/sign_up')" type="button">Sign Up</button> </div>
        <% end %>

      </div>
      <div class="navbar-item">
        <%= form_with(url: search_products_path, method: :get, local: true) do %>
            <div class="field is-ground mb-5 has-addons">
              <div class="control">
                <%= text_field_tag(:keywords, nil, class: "input is-info", placeholder: 'Search for product') %>
              </div>
              <div class="control">
                <%= select_tag(:category, options_from_collection_for_select(Category.all, "id", "category_name"), :include_blank => 'All', class: "dropdown") %>
              </div>
              <div class="control">
                <%=submit_tag("Search", class: "button is-primary")%>
              </div>
            </div>
        <% end %>
      </div>
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GreenBean</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://unpkg.com/mvp.css@1.12/mvp.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma-rtl.min.css">
    <script src="https://js.stripe.com/v3"></script>
  </head>

  <body>
    <%= render "layouts/menu" %>
    <%= yield %>
  </body>
</html>